services:
  sb-relay:
    image: ghcr.io/krabdo/sb-relay-shoutrrr:shoutrrr-preview
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - sb-relay-data:/data
    security_opt:
      - no-new-privileges:true

volumes:
  sb-relay-data:
